export const PLAYER_CONFIG = {
  DEPTH: 5, 
  SCALE: 1,
  BODY_SIZE: {
    x: 32,
    y: 48
  },
  MASS: 10,
  MAXHP: 4,
  SPEED: 128,
  ATTACK_DAMAGE: 2,
  ATTACK_COOLDOWN: 0,
  ATTACK_DETECTION_ZONE: {
    w: 160,
    h: 176,
  },
  ATTACK_ZONE: {},
  DASH_COOLDOWN: 1200
}

export const CLONE_CONFIG = {
  DEPTH: PLAYER_CONFIG.DEPTH - 1,
  SCALE: PLAYER_CONFIG.SCALE,
  BODY_SIZE: PLAYER_CONFIG.BODY_SIZE,
  MASS: PLAYER_CONFIG.MASS / 2,
  MAXHP: PLAYER_CONFIG.MAXHP / 2,
  SPEED: PLAYER_CONFIG.SPEED,
  ATTACK_DAMAGE: PLAYER_CONFIG.ATTACK_DAMAGE * 2,
  ATTACK_COOLDOWN: PLAYER_CONFIG.ATTACK_COOLDOWN,
  ATTACK_DETECTION_ZONE: PLAYER_CONFIG.ATTACK_DETECTION_ZONE,
  ATTACK_ZONE: PLAYER_CONFIG.ATTACK_ZONE,
  DASH_COOLDOWN: PLAYER_CONFIG.DASH_COOLDOWN,
  ANCHOR_OFFSET: 150,
}